version: '3'


services:
     db:
        image: mysql:5.7
        environment:
                MYSQL_ROOT_PASSWORD: school1
                MYSQL_DATABASE: webserver
                MYSQL_USER: oracle
                MYSQL_PASSWORD: school1
     wordpress:
         image: wordpress
         ports:
            - '99:80'
         environment:
                WORDPRESS_DB_HOST: db:3306
                WORDPRESS_DB_USER: oracle
                WORDPRESS_DB_PASSWORD: school1
                WORDPRESS_DB_NAME: webserver